<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e85f5256-aaf1-4b96-bea1-2725166a84e1</testSuiteGuid>
   <testCaseLink>
      <guid>b5a54b65-a3eb-4273-9715-8bd293b6da06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestEmployee/Verify that created account successful</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cd2290b0-2c90-479b-9bbe-7882799bab1b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EmployeeData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cd2290b0-2c90-479b-9bbe-7882799bab1b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Name</value>
         <variableId>e90f88c4-c7ae-49b2-8e23-06478ff02a77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fc16943-d755-43b8-ae0f-4bfbd8f3d79a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd951ef1-ae15-44f2-a074-b2f5443ceb13</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
